### ISSUE TITLE
irqbalance spamming syslog

### ISSUE THREAD

**Issue by konradsa** [Irqbalance/irqbalance#29]
Why is irqbalance spamming syslog constantly with the following messages?

`
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR meson_uart
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_pcd
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR dwc_otg_hcd:usb1
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR deinterlace
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR hdmitx
Feb 11 11:33:28 odroid64 /usr/sbin/irqbalance: GUESSING AARCH64 CLASS FOR TIMER-F
`

`
odroid@odroid64:/var/log$ grep 'GUESSING AARCH64' /var/log/syslog | wc -l
102591
`

This is when running it on an ODROID C2, running Ubuntu 16.04 LTS distribution.

This is how it was brought up by startup script, it should be running in debug mode:
`
00:00:07 /usr/sbin/irqbalance --pid=/var/run/irqbalance.pid
`

**Comment by ppwaskie** [comment]
It looks like it's having trouble guessing the base ARM architecture.  This
was a recent addition to irqbalance, so I suspect that given all the
different board layouts out there we still have some kinks to work out.

I can see about trying to test this on one of my ARM-based boards, but
they're not readily available for me at the moment (tied up in projects).
But I'll see what I can do in the short-term.

Also, what version of irqbalance are you running?

**Comment by sikarash** [comment]
It looks like syslog(LOG_DEBUG, "GUESSING AARCH64 CLASS FOR %s\n", ...) showing them.
If you hate LOG_DEBUG messages, you need to change the system log level to LOG_INFO or above.

**Comment by ppwaskie** [comment]
To be honest, this sounds more like a syslogd config issue than anything.
My initial thought was irqbalance was having trouble identifying the
board.  But I don't think that's the case here.

**Comment by konradsa** [comment]
I am running Version: 1.1.0-2ubuntu1

Any suggestion on what could be mis-configured? Googling didn't reval anything, and I also don't see any other tasks logging debug messages in syslog.

**Comment by konradsa** [comment]
Anybody?

**Comment by nhorman** [comment]
A few questions:
Is ubuntu using systemd, or is it using an older init system?

Are you starting irqbalance with the --journal option?

I'm going to guess that you are not using systemd and are using the --journal option, as that would cause everything to just dump out on the console.

**Comment by nhorman** [comment]
closing for lack of respone, please reopen if you come back to this

**Comment by late-latte** [comment]
I'm not sure if I should revive this, but irqbalance still spamming "GUESSING..." till today.

- Odroid C2
- systemd 238
- irqbalance 1.3.0, as packaged by Arch Linux ARM
- Linux 3.14.79-28-ARCH #1 SMP PREEMPT Tue Nov 28 20:47:59 MST 2017 aarch64 GNU/Linux (haven't tried mainstream linux-aarch64 because I need USB access)
- Vanilla /usr/lib/systemd/system/irqbalance.service
- $IRQBALANCE_ARGS is --journal balance_level=core (still logging "GUESSING..." even without those options)

It amassed  ~300 MB worth of journal just within 2 days after accounting for other logs, so it's really harmful for eMMC write cycles. I'm using an overlay from a hard disk at the moment to minimize the damage, which is why I haven't tried using mainline kernel.

Let me know if you need other info. I hope you can fix this soon, or maybe just add no logging option in future releases for the time being.

**Comment by nhorman** [comment]
Ok, so you've confirmed that you are using system, which was my first question.  The next thing you need to do now is adjust the log level filter in journald.conf.  there is a setting there called MaxLevelStore (I think).  Set it to 'info' and that should drop all LOG_DEBUG messages prior to writing them to disk.

**Comment by late-latte** [comment]
I don't know about OP, but I do use systemd.

Altering MaxLevelStore is slightly problematic because it still constantly spams "Respamming cpu topology" and info about isolated, adaptive-ticks, and banned CPUs. Reducing MaxLevelStore to Notice does the trick of completely silencing it, but at the cost of me not being able to log unbound, etc properly. Is there another, more local solution?

**Comment by nhorman** [comment]
Well, that would be because the devices that have registered interrupts don't currently match anything in the match array.  Please return your MaxLevelSTore value to debug, and run irqbalance in the foreground, and post the results here.  We need to see what the irq names are so we can develop regexs for them appropriately.

**Comment by nhorman** [comment]
yeah, your posts are somehow getting filtered, you should probably figure that out or its going to take forever to fix.  I've updated the branch above, adding some debug code to detect the causee for the rescan, which should help us figure out how to fix this

**Comment by late-latte** [comment]
Oh damn I thought the proposed fix has been merged to master. Sorry. I'll stick with the branch from now on.

Here's the log:
This machine seems not NUMA capable.
Isolated CPUs: 00000000
Adaptive-ticks CPUs: 00000000
Banned CPUs: 00000000
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)
IRQ vgic(25) guessed as class 0
IRQ vsync(35) guessed as class 0
IRQ eth0(40) guessed as class 5
IRQ eth0(40) guessed as class 0
IRQ meson_uart(58) guessed as class 0
IRQ dwc_otg_pcd(62) guessed as class 0
IRQ dwc_otg_hcd:usb1(63) guessed as class 0
IRQ TIMER-F(92) guessed as class 0
IRQ TIMER-G(93) guessed as class 0
IRQ TIMER-H(94) guessed as class 0
IRQ TIMER-I(95) guessed as class 0
IRQ sd_emmc_mmc_in(99) guessed as class 0
IRQ sd_emmc_mmc_out(101) guessed as class 0
IRQ rdma(121) guessed as class 0
IRQ ge2d(182) guessed as class 0
IRQ Mali_GP(192) guessed as class 0
IRQ Mali_GP_MMU(193) guessed as class 0
IRQ Mali_PP_Broadcast(194) guessed as class 0
IRQ Mali_PP0(196) guessed as class 0
IRQ Mali_PP0_MMU(197) guessed as class 0
IRQ Mali_PP1(198) guessed as class 0
IRQ Mali_PP1_MMU(199) guessed as class 0
IRQ Mali_PP2(200) guessed as class 0
IRQ Mali_PP2_MMU(201) guessed as class 0
IRQ meson_uart(225) guessed as class 0
IRQ 241(241) guessed as class 0
IRQ 242(242) guessed as class 0
IRQ sd_emmc(249) guessed as class 0
IRQ sd_emmc(250) guessed as class 0
NUMA NODE NUMBER: -1
LOCAL CPU MASK: ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff

CANT FIND INFO FOR irq 25, RESCANNING



-----------------------------------------------------------------------------
CANT FIND INFO FOR irq 25, RESCANNING
Rescanning cpu topology 
Isolated CPUs: 00000000
Adaptive-ticks CPUs: 00000000
Banned CPUs: 00000000
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)
IRQ vgic(25) guessed as class 0
IRQ vsync(35) guessed as class 0
IRQ eth0(40) guessed as class 5
IRQ eth0(40) guessed as class 0
IRQ meson_uart(58) guessed as class 0
IRQ dwc_otg_pcd(62) guessed as class 0
IRQ dwc_otg_hcd:usb1(63) guessed as class 0
IRQ TIMER-F(92) guessed as class 0
IRQ TIMER-G(93) guessed as class 0
IRQ TIMER-H(94) guessed as class 0
IRQ TIMER-I(95) guessed as class 0
IRQ sd_emmc_mmc_in(99) guessed as class 0
IRQ sd_emmc_mmc_out(101) guessed as class 0
IRQ rdma(121) guessed as class 0
IRQ ge2d(182) guessed as class 0
IRQ Mali_GP(192) guessed as class 0
IRQ Mali_GP_MMU(193) guessed as class 0
IRQ Mali_PP_Broadcast(194) guessed as class 0
IRQ Mali_PP0(196) guessed as class 0
IRQ Mali_PP0_MMU(197) guessed as class 0
IRQ Mali_PP1(198) guessed as class 0
IRQ Mali_PP1_MMU(199) guessed as class 0
IRQ Mali_PP2(200) guessed as class 0
IRQ Mali_PP2_MMU(201) guessed as class 0
IRQ meson_uart(225) guessed as class 0
IRQ 241(241) guessed as class 0
IRQ 242(242) guessed as class 0
IRQ sd_emmc(249) guessed as class 0
IRQ sd_emmc(250) guessed as class 0
CANT FIND INFO FOR irq 25, RESCANNING
^CCANT FIND INFO FOR irq 25, RESCANNING
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)

**Comment by nhorman** [comment]
ok, so that shows us that we're re scanning because somehow, after detecting the irq we didn't add it properly to the irq database.  I've updated the issue branch to figure out where thats failing.  Please pull the branch, rebuild, and re-run, and lets see if we can pinpoint whats going wrong

**Comment by late-latte** [comment]
I've doubled check the branch, the commit, and recompiled.
There doesn't seem like any change.

This machine seems not NUMA capable.
Isolated CPUs: 00000000
Adaptive-ticks CPUs: 00000000
Banned CPUs: 00000000
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)
IRQ vgic(25) guessed as class 0
IRQ vsync(35) guessed as class 0
IRQ eth0(40) guessed as class 5
IRQ eth0(40) guessed as class 0
IRQ meson_uart(58) guessed as class 0
IRQ dwc_otg_pcd(62) guessed as class 0
IRQ dwc_otg_hcd:usb1(63) guessed as class 0
IRQ TIMER-F(92) guessed as class 0
IRQ TIMER-G(93) guessed as class 0
IRQ TIMER-H(94) guessed as class 0
IRQ TIMER-I(95) guessed as class 0
IRQ sd_emmc_mmc_in(99) guessed as class 0
IRQ sd_emmc_mmc_out(101) guessed as class 0
IRQ rdma(121) guessed as class 0
IRQ ge2d(182) guessed as class 0
IRQ Mali_GP(192) guessed as class 0
IRQ Mali_GP_MMU(193) guessed as class 0
IRQ Mali_PP_Broadcast(194) guessed as class 0
IRQ Mali_PP0(196) guessed as class 0
IRQ Mali_PP0_MMU(197) guessed as class 0
IRQ Mali_PP1(198) guessed as class 0
IRQ Mali_PP1_MMU(199) guessed as class 0
IRQ Mali_PP2(200) guessed as class 0
IRQ Mali_PP2_MMU(201) guessed as class 0
IRQ meson_uart(225) guessed as class 0
IRQ 241(241) guessed as class 0
IRQ 242(242) guessed as class 0
IRQ sd_emmc(249) guessed as class 0
IRQ sd_emmc(250) guessed as class 0
NUMA NODE NUMBER: -1
LOCAL CPU MASK: ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff

CANT FIND INFO FOR irq 25, RESCANNING



-----------------------------------------------------------------------------
CANT FIND INFO FOR irq 25, RESCANNING
Rescanning cpu topology 
Isolated CPUs: 00000000
Adaptive-ticks CPUs: 00000000
Banned CPUs: 00000000
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)
IRQ vgic(25) guessed as class 0
IRQ vsync(35) guessed as class 0
IRQ eth0(40) guessed as class 5
IRQ eth0(40) guessed as class 0
IRQ meson_uart(58) guessed as class 0
IRQ dwc_otg_pcd(62) guessed as class 0
IRQ dwc_otg_hcd:usb1(63) guessed as class 0
IRQ TIMER-F(92) guessed as class 0
IRQ TIMER-G(93) guessed as class 0
IRQ TIMER-H(94) guessed as class 0
IRQ TIMER-I(95) guessed as class 0
IRQ sd_emmc_mmc_in(99) guessed as class 0
IRQ sd_emmc_mmc_out(101) guessed as class 0
IRQ rdma(121) guessed as class 0
IRQ ge2d(182) guessed as class 0
IRQ Mali_GP(192) guessed as class 0
IRQ Mali_GP_MMU(193) guessed as class 0
IRQ Mali_PP_Broadcast(194) guessed as class 0
IRQ Mali_PP0(196) guessed as class 0
IRQ Mali_PP0_MMU(197) guessed as class 0
IRQ Mali_PP1(198) guessed as class 0
IRQ Mali_PP1_MMU(199) guessed as class 0
IRQ Mali_PP2(200) guessed as class 0
IRQ Mali_PP2_MMU(201) guessed as class 0
IRQ meson_uart(225) guessed as class 0
IRQ 241(241) guessed as class 0
IRQ 242(242) guessed as class 0
IRQ sd_emmc(249) guessed as class 0
IRQ sd_emmc(250) guessed as class 0
CANT FIND INFO FOR irq 25, RESCANNING
CANT FIND INFO FOR irq 25, RESCANNING
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)

**Comment by nhorman** [comment]
That's very odd.  Can you run the git show command and provide the commit hash that it shows you?

**Comment by late-latte** [comment]
commit 88be7c1c38ae6a29652e9404a75d2b804061d648 (HEAD -> master)
Merge: 05d87e1 0a2a3e6

**Comment by nhorman** [comment]
your HEAD commit should be 0a2a3e6ba7e7fc8fa379577f214626211f50ca82.  It seems like you merged in some additional changes of yours when you did a pull.  It looks like those came from the main branch, which should be fine, but to be sure we're running the same code, please fix your branch to be on the proper commit (or just re-clone the tree).  And re-run the test?

**Comment by nhorman** [comment]
Ok, thank you for that.  So, this is getting somewhat odd.  Based on what we have here:

1) We know that we detect irq 25 during the rescan, based on the fact that we get this printf:
IRQ vgic(25) guessed as class 0
2) because of the code flow through collect_full_irq_list we can see that irq 25 should have been added to the tmp_irqs list which is returned to the caller (rebuild_irq_db)
3) rebuild_irq_db should call add_missing_irq for every irq on the list, which with our new debug code should print out a line per interrupt.
4) Because we don't see any of those printfs, the tmp_irq list is either empty or corrupt in some way.

At this point, I feel like I need to start running this through some debug tools.  Could you please send me a copy of your /proc/interrupts file?  Please attach it, rather than paste it here, to preserve formatting.  I'll see if I can't recreate the issue here and figure out whats going on.

**Comment by late-latte** [comment]
[proc.interrupts.txt](https://github.com/Irqbalance/irqbalance/files/2025836/proc.interrupts.txt)

*I randomly assigned extension because github won't allow me otherwise, but it's typical vim-able file.

**Comment by nhorman** [comment]
Ok, the good news is I have a emulated aarch64 system setup on kvm and, with your proc/interrupts file, the issue is reproducing.  I'll see if I can't get this debugged tomorrow.

**Comment by late-latte** [comment]
Alright. Thanks for your effort!

**Comment by nhorman** [comment]
hmm, unfortunately I was mistaken.  I had the same symptom as you, in that I was continually rescanning my topology, but it was because you had a different number of cpus on your system that I.  As soon I as brought the cpu count into line, it worked fine.  So I guess we're back to debugging at your site.  I've pushed some more debug code to the issue-29 branch that should dump out the proc/ionterrupts code as you read it so we can try to see whats going on as the program runs. Please run it for several minutes with the -f and -d options, record all the output and post it here.  Thanks!

**Comment by late-latte** [comment]
Aw, too bad. Here's the file you asked.

[debug.txt](https://github.com/Irqbalance/irqbalance/files/2040665/debug.txt)

**Comment by nhorman** [comment]
Ok, one more test, I think I found the problem.  Description should be in the HEAD commit on the issue-29 branch

**Comment by nhorman** [comment]
sorry, to be clear, please give the branch a run on your system.  Thanks!

**Comment by late-latte** [comment]
Yay, it stops rescanning! It did print out /proc/interrupts regularly, but I assumed that's what 989f555 commit was intended for. Thanks a lot!

For your perusal: [debug.txt](https://github.com/Irqbalance/irqbalance/files/2046696/debug.txt)

**Comment by nhorman** [comment]
awesome, I'll clean up the debug changes and merge the branch to master.  Thanks!

**Comment by nhorman** [comment]
https://github.com/Irqbalance/irqbalance/pull/66

Fixed

**Comment by late-latte** [comment]
Hi,

Not sure if you didn't notice my edited input (maybe because you read this via email notif or something similar?), but there are still remaining lines to be sorted out via attachment debug1.txt. Hopefully you still want to put extra work for this.

I've already run the new binary from master. It still shows the aforementioned lines.

**Comment by nhorman** [comment]
I did, though I'm not sure what you've done to your tree. Line 266 in the master branch is a comment, so commenting it out is meaningless (it also suggests that theres something different in your tree from whats in the upstream repository).  also, I presume the printouts that you're referring to are the "Trying to add" and "adding" lines?  Those were debug printouts that were reverted with commit 88751f2430ddfdba211fa1c3037793feafefd3ff.  Can you try re-cloning the tree to ensure you have the most up to date code?

**Comment by late-latte** [comment]
Line 266 of the past issue-29 branch (undoing 989f55546e553ce74aed3ddb506aad12040da890), but by now it had indeed been fixed with the commit you mentioned. Regardless, I had rm -rf'ed the issue-29 and recloned the master, just to see if there's debug code somewhere I've missed and master cleanup fixed that, but the remaining recurring printout is still the same:

-----------------------------------------------------------------------------
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)



-----------------------------------------------------------------------------
Package -1:  numa_node cpu mask is 00000001 (load 0)
        Cache domain 0:  numa_node is cpu mask is 00000001  (load 0) 
                CPU number 0  numa_node is (load 10000000)
Package -1:  numa_node cpu mask is 00000002 (load 0)
        Cache domain 1:  numa_node is cpu mask is 00000002  (load 0) 
                CPU number 1  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000004 (load 0)
        Cache domain 2:  numa_node is cpu mask is 00000004  (load 0) 
                CPU number 2  numa_node is (load 0)
Package -1:  numa_node cpu mask is 00000008 (load 0)
        Cache domain 3:  numa_node is cpu mask is 00000008  (load 0) 
                CPU number 3  numa_node is (load 0)

Perhaps it's entirely unrelated with the rescanning bug? And it had always been there since the beginning along with the rescanning output.

**Comment by nhorman** [comment]
Thats not a bug, those are console messages that are meant to be there.  You turn them off by setting your log level to something higer than INFO (see my comments previously about MaxLevelStore)

**Comment by late-latte** [comment]
Ah, sorry, you're right. Do note that even if the aforementioned output is shown with --debug when directly run, it doesn't print out to journald log (unless with explicit --debug specified in irqbalance.service) on DEBUG level, so it's not necessary to set it as INFO. Once again, thanks! I'll notify the downstream straight away.
